
Behavior: Strict

#"Strict" - Kick clients with blacklisted mods + Kick non Hand-shaker mod clients
#"Vanilla" - Kick clients with blacklisted mods but ignoring non Hand-shaker mod clients (Could be dangeours if clients spoofs clients)

Kick Message: "You are using a blacklisted mod: {mod}. Please remove it to join this server."

Missing mod message: "To connect to this server please download 'Hand-shaker' mod."

Blacklisted Mods:
- xraymod
- testmod
- forge