name: HandShaker
version: ${version}
main: me.mklv.handshaker.paper.HandShakerPlugin
description: Client mod handshake and blacklist validation
authors:
  - IceVallish / Suskese
api-version: "1.21"
folia-supported: true
permissions:
  handshaker.admin:
    description: Allows access to HandShaker admin commands
    default: op
  handshaker.bypass:
    description: Bypass mod blacklist/whitelist checks
    default: false
